project_id = "hmeqkozvnmoimfwiqebz"

[functions.generate-leap-of-faith]
verify_jwt = false

[functions.generate-mom-test]
verify_jwt = false

[functions.generate-business-image]
verify_jwt = false

[functions.fetch-predicthq-events]
verify_jwt = false